name: smu-notice-bot
on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run crawler
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
      - name: Persist state
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update seen notices"
          file_pattern: state.json
